# makefile

# bash

JAVAC = javac
SOURCES = assignment3.java
SUFFIXES = .class .java
FLAGS = -g

assignment3.class: assignment3.java
	$(JAVAC) $(FLAGS) assignment3.java

clean:
	@rm *.class

run:
	java assignment3
