# makefile

# bash

JAVAC = javac
SOURCES = assignment2.java BinarySearchTree.java Node.java
SUFFIXES = .class .java
FLAGS = -g

assignment2.class: assignment2.java
	$(JAVAC) $(FLAGS) assignment2.java

clean:
	@rm *.class

run:
	java assignment2
